# Generated by Django 5.0.6 on 2024-10-01 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_aboutpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aboutpage',
        ),
    ]
